ALTER TABLE "Event" ADD COLUMN "celebrationType" TEXT NOT NULL DEFAULT 'WEDDING';
ALTER TABLE "Event" ADD COLUMN "traditions" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Event" ADD COLUMN "planningPreferences" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
