import { useEffect, useState } from 'react';
import { Box, CalendarClock, Check, ChevronDown, ChevronUp, Circle, Clock3, MapPin, Navigation, Package, Phone, ShieldCheck, Store, Truck } from 'lucide-react';
import { apiRequest } from '@/lib/api';

interface OrderItem { id: string; name: string; quantity: number; unitPrice: number; fulfillmentId?: string; }
interface DeliveryEvent { id: string; status: string; label: string; detail?: string; location?: string; occurredAt: string; }
interface Fulfillment { id: string; trackingCode: string; status: string; method: string; handoffMethod: string; recipientName: string; county: string; addressLine: string; landmark?: string; deliveryPin?: string; estimatedStart?: string; estimatedEnd?: string; courierName?: string; courierPhone?: string; trackingUrl?: string; vendor?: { businessName: string; slug: string; whatsapp?: string }; items: OrderItem[]; events: DeliveryEvent[]; }
interface Order { id: string; orderNumber: string; status: string; paymentStatus: string; currency: string; subtotal: number; deliveryFee: number; total: number; createdAt: string; items: OrderItem[]; fulfillments: Fulfillment[]; }

const stages = ['PENDING', 'PREPARING', 'READY_FOR_PICKUP', 'PICKED_UP', 'IN_TRANSIT', 'ARRIVING', 'DELIVERED'];
const stageLabel: Record<string, string> = { PENDING: 'Confirmed', PREPARING: 'Preparing', READY_FOR_PICKUP: 'Ready', COURIER_ASSIGNED: 'Courier assigned', PICKED_UP: 'Picked up', IN_TRANSIT: 'On the way', ARRIVING: 'Arriving', DELIVERED: 'Delivered', DELIVERY_FAILED: 'Delivery issue', RETURN_REQUESTED: 'Return requested', RETURNING: 'Returning', RETURNED: 'Returned', CANCELLED: 'Cancelled' };
const activeStage = (status: string) => Math.max(0, stages.indexOf(status === 'COURIER_ASSIGNED' ? 'READY_FOR_PICKUP' : status));
const money = (amount: number, currency: string) => new Intl.NumberFormat('en-KE', { style: 'currency', currency, maximumFractionDigits: 0 }).format(Number(amount));

export function Orders() {
  const [orders, setOrders] = useState<Order[]>([]);
  const [expanded, setExpanded] = useState<string>('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  useEffect(() => { apiRequest<Order[]>('/orders').then((result) => { setOrders(result); const firstActive = result.flatMap((order) => order.fulfillments).find((item) => item.status !== 'DELIVERED'); if (firstActive) setExpanded(firstActive.id); }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Unable to load orders.')).finally(() => setLoading(false)); }, []);

  return <div className="space-y-7 animate-in fade-in duration-500 pt-2">
    <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3"><div><div className="flex items-center gap-2 text-primary text-xs font-bold uppercase tracking-widest"><Navigation className="h-4 w-4" /> Live fulfilment</div><h1 className="text-3xl font-extrabold mt-2">Orders & delivery</h1><p className="text-gray-500 mt-1">From seller preparation to secure handoff, every step stays visible.</p></div><div className="rounded-full bg-green-50 text-green-700 text-xs font-bold px-4 py-2 flex items-center gap-2"><ShieldCheck className="h-4 w-4" /> PIN-protected delivery</div></div>
    {loading && <div className="bg-white rounded-3xl border p-10 text-center text-gray-500">Loading your orders…</div>}
    {error && <div role="alert" className="rounded-2xl bg-red-50 p-4 text-red-700">{error}</div>}
    {!loading && !error && orders.length === 0 && <div className="bg-white rounded-3xl border p-12 text-center"><Package className="h-10 w-10 text-gray-300 mx-auto mb-3"/><p className="font-bold">No orders yet</p><p className="text-sm text-gray-500 mt-1">Your delivery timeline will appear after checkout.</p></div>}
    <div className="space-y-7">{orders.map((order) => <article key={order.id} className="bg-white rounded-[28px] border border-border-soft shadow-sm overflow-hidden">
      <header className="bg-[#171735] text-white p-6 md:p-7 flex flex-col md:flex-row md:items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-[11px] uppercase tracking-[0.15em] text-white/50"><Box className="h-3.5 w-3.5" /> {new Date(order.createdAt).toLocaleDateString('en-KE', { day: 'numeric', month: 'short', year: 'numeric' })}</div><h2 className="font-extrabold text-xl mt-2">Order {order.orderNumber}</h2></div><div className="flex gap-6"><div><p className="text-[10px] uppercase text-white/45 font-bold">Payment</p><p className="text-sm font-bold mt-1">{order.paymentStatus.replaceAll('_', ' ')}</p></div><div><p className="text-[10px] uppercase text-white/45 font-bold">Total</p><p className="text-sm font-bold mt-1">{money(order.total, order.currency)}</p></div></div></header>
      <div className="p-5 md:p-7 space-y-5">
        {order.fulfillments.length ? order.fulfillments.map((delivery) => {
          const current = activeStage(delivery.status); const isExpanded = expanded === delivery.id;
          return <section key={delivery.id} className="rounded-2xl border border-gray-200 overflow-hidden">
            <button onClick={() => setExpanded(isExpanded ? '' : delivery.id)} className="w-full p-5 flex items-center justify-between gap-4 text-left hover:bg-gray-50"><div className="flex items-center gap-4 min-w-0"><div className={`w-12 h-12 rounded-2xl flex items-center justify-center shrink-0 ${delivery.status === 'DELIVERED' ? 'bg-green-100 text-green-700' : 'bg-primary/10 text-primary'}`}>{delivery.status === 'DELIVERED' ? <Check className="h-5 w-5"/> : <Truck className="h-5 w-5"/>}</div><div className="min-w-0"><p className="font-extrabold truncate">{delivery.vendor?.businessName ?? 'Merry Tales Studio'}</p><p className="text-sm text-gray-500 mt-0.5">{stageLabel[delivery.status] ?? delivery.status.replaceAll('_',' ')} · {delivery.trackingCode}</p></div></div>{isExpanded ? <ChevronUp className="h-5 w-5 text-gray-400"/> : <ChevronDown className="h-5 w-5 text-gray-400"/>}</button>
            <div className="px-5 pb-5"><div className="grid grid-cols-7 gap-1 items-start">{stages.map((stage, index) => <div key={stage} className="text-center"><div className="flex items-center"><div className={`h-1 flex-1 ${index <= current ? 'bg-primary' : 'bg-gray-200'} ${index === 0 ? 'invisible' : ''}`}/><div className={`w-3 h-3 rounded-full border-2 shrink-0 ${index <= current ? 'bg-primary border-primary' : 'bg-white border-gray-300'}`}/><div className={`h-1 flex-1 ${index < current ? 'bg-primary' : 'bg-gray-200'} ${index === stages.length - 1 ? 'invisible' : ''}`}/></div><p className={`hidden sm:block text-[10px] mt-2 ${index <= current ? 'font-bold text-foreground' : 'text-gray-400'}`}>{stageLabel[stage]}</p></div>)}</div></div>
            {isExpanded && <div className="border-t bg-gray-50 p-5 animate-in fade-in duration-200">
              <div className="grid md:grid-cols-[1fr_280px] gap-6"><div><h3 className="text-sm font-extrabold mb-4">Delivery activity</h3><div className="space-y-0">{delivery.events.map((event, index) => <div key={event.id} className="flex gap-3"><div className="flex flex-col items-center"><div className={`w-7 h-7 rounded-full flex items-center justify-center ${index === delivery.events.length - 1 ? 'bg-primary text-white' : 'bg-white border text-gray-400'}`}>{index === delivery.events.length - 1 ? <Check className="h-3.5 w-3.5"/> : <Circle className="h-2 w-2 fill-current"/>}</div>{index < delivery.events.length - 1 && <div className="w-px h-10 bg-gray-200"/>}</div><div className="pb-5"><p className="text-sm font-bold">{event.label}</p><p className="text-xs text-gray-500 mt-0.5">{new Date(event.occurredAt).toLocaleString('en-KE')}{event.location ? ` · ${event.location}` : ''}</p>{event.detail && <p className="text-xs text-gray-600 mt-1">{event.detail}</p>}</div></div>)}</div></div>
                <aside className="space-y-3"><div className="bg-white border rounded-2xl p-4"><div className="flex items-center gap-2 text-xs font-bold text-gray-500"><CalendarClock className="h-4 w-4 text-primary"/> Estimated delivery</div><p className="font-bold text-sm mt-2">{delivery.estimatedStart ? `${new Date(delivery.estimatedStart).toLocaleDateString('en-KE', { day: 'numeric', month: 'short' })} – ${new Date(delivery.estimatedEnd ?? delivery.estimatedStart).toLocaleDateString('en-KE', { day: 'numeric', month: 'short' })}` : 'Confirming shortly'}</p></div><div className="bg-white border rounded-2xl p-4"><div className="flex items-center gap-2 text-xs font-bold text-gray-500"><MapPin className="h-4 w-4 text-primary"/> Handoff location</div><p className="font-bold text-sm mt-2">{delivery.addressLine}</p><p className="text-xs text-gray-500">{delivery.landmark ? `${delivery.landmark}, ` : ''}{delivery.county}</p></div>{delivery.deliveryPin && delivery.status !== 'DELIVERED' && <div className="bg-[#171735] text-white rounded-2xl p-4"><div className="flex items-center gap-2 text-xs font-bold text-white/55"><ShieldCheck className="h-4 w-4 text-primary"/> Delivery PIN</div><p className="text-3xl tracking-[0.28em] font-extrabold mt-2">{delivery.deliveryPin}</p><p className="text-[11px] text-white/55 mt-2">Share only after receiving and checking your package.</p></div>}{delivery.courierName && <div className="bg-white border rounded-2xl p-4"><div className="flex items-center gap-2 text-xs font-bold text-gray-500"><Truck className="h-4 w-4 text-primary"/> Courier</div><p className="font-bold text-sm mt-2">{delivery.courierName}</p>{delivery.courierPhone && <a href={`tel:${delivery.courierPhone}`} className="text-xs text-primary font-bold flex items-center gap-1 mt-1"><Phone className="h-3 w-3"/> Call courier</a>}</div>}</aside></div>
              <div className="mt-5 pt-4 border-t"><p className="text-xs font-bold text-gray-500 mb-2">In this delivery</p><div className="flex flex-wrap gap-2">{delivery.items.map((item) => <span key={item.id} className="bg-white border rounded-full px-3 py-1.5 text-xs font-semibold">{item.quantity}× {item.name}</span>)}</div></div>
            </div>}
          </section>;
        }) : <div className="rounded-2xl bg-purple-50 text-purple-800 p-5 flex items-center gap-3"><Store className="h-5 w-5"/><div><p className="font-bold text-sm">Digital or service order</p><p className="text-xs mt-0.5">No physical delivery is required for this order.</p></div></div>}
        <div className="flex items-center justify-between text-sm pt-2"><div className="flex items-center gap-2 text-gray-500"><Clock3 className="h-4 w-4"/> Updates are recorded in your order timeline</div><div className="font-semibold">Delivery {money(order.deliveryFee ?? 0, order.currency)}</div></div>
      </div>
    </article>)}</div>
  </div>;
}
