import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import { rateLimit } from 'express-rate-limit';
import { allowedOrigins } from './config';
import { authRouter } from './routes/auth';
import { eventsRouter } from './routes/events';
import { vendorsRouter } from './routes/vendors';
import { leadsRouter } from './routes/leads';
import { operationsRouter } from './routes/operations';
import { notificationsRouter } from './routes/notifications';
import { paymentsRouter } from './routes/payments';
import { uploadsRouter, uploadRoot } from './routes/uploads';
import { productsRouter } from './routes/products';
import { ordersRouter } from './routes/orders';
import { financeRouter } from './routes/finance';
import { commercialRouter } from './routes/commercial';
import { assistantRouter } from './routes/assistant';
import { engagementRouter } from './routes/engagement';
import { errorHandler, notFound } from './middleware/errors';

export const app = express();
app.disable('x-powered-by');
app.use(helmet());
app.use(cors({ origin: allowedOrigins, credentials: true }));
app.use(express.json({ limit: '1mb' }));
app.use('/api', rateLimit({ windowMs: 15 * 60_000, limit: 500, standardHeaders: 'draft-8', legacyHeaders: false }));
app.use('/api/auth/login', rateLimit({ windowMs: 15 * 60_000, limit: 10, standardHeaders: 'draft-8', legacyHeaders: false }));
app.use('/api/auth/register', rateLimit({ windowMs: 60 * 60_000, limit: 5, standardHeaders: 'draft-8', legacyHeaders: false }));

app.get('/api/health', (_req, res) => res.json({ data: { status: 'ok', service: 'merry-tales-api' } }));
app.use('/api/auth', authRouter);
app.use('/api/events', eventsRouter);
app.use('/api/vendors', vendorsRouter);
app.use('/api/products', productsRouter);
app.use('/api/orders', ordersRouter);
app.use('/api/finance', financeRouter);
app.use('/api/commercial', commercialRouter);
app.use('/api/assistant', assistantRouter);
app.use('/api/engagement', engagementRouter);
app.use('/api/leads', leadsRouter);
app.use('/api/operations', operationsRouter);
app.use('/api/notifications', notificationsRouter);
app.use('/api/payments', paymentsRouter);
app.use('/api/uploads', uploadsRouter);
app.use('/uploads', express.static(uploadRoot, { fallthrough: false, maxAge: '1d' }));
app.use(notFound);
app.use(errorHandler);
