import { ArrowRight, Banknote, Building2, CheckCircle2, Gift, MessageSquareText, PackageCheck, Plug, ShieldCheck, Smartphone } from 'lucide-react';
import { Button } from '@/components/ui/button';

const partnerTypes = [
  { icon: Gift, title: 'Gifting & voucher partners', names: 'GiftPesa, eZawadi and other verified issuers', copy: 'Partner-issued vouchers, partial redemption, corporate rewards and recipient choice.' },
  { icon: Banknote, title: 'Banks & payment providers', names: 'Banks, authorized PSPs and payment networks', copy: 'Collections, safeguarded settlement, cards, cross-border payments, refunds and reconciliation.' },
  { icon: Smartphone, title: 'Mobile money', names: 'M-Pesa and other approved rails', copy: 'Familiar checkout, payment confirmation, disbursements and merchant settlement.' },
  { icon: MessageSquareText, title: 'Communication', names: 'MobileSasa and messaging providers', copy: 'Consent-aware SMS, invitations, reminders, gift delivery and operational notifications.' },
  { icon: PackageCheck, title: 'Fulfilment & logistics', names: 'Couriers, fleets, pickup networks and gift fulfilment', copy: 'Scheduled delivery, wrapping, proof of delivery, returns and event-day logistics.' },
  { icon: Building2, title: 'Enterprise & institutions', names: 'Employers, insurers, SACCOs, associations and event organizers', copy: 'Corporate gifting, employee milestones, procurement, delegate packs and member benefits.' },
];

const integrationRules = ['Verified legal and regulatory standing', 'Secure APIs, signed webhooks and reconciliation', 'Clear consumer ownership and complaint handling', 'Data minimization and no unauthorized cross-marketing', 'Sandbox, service levels and incident response', 'Transparent fees, settlement and refund responsibilities'];

export function Partners() {
  return <div className="min-h-screen pt-20 bg-white">
    <section className="bg-[#171735] px-4 py-20 text-white sm:px-6 md:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><div className="inline-flex items-center gap-3 text-pink-300"><span className="relative grid h-8 w-8 place-items-center border border-pink-300/40 before:absolute before:-left-1.5 before:-top-1.5 before:h-3 before:w-3 before:border-l before:border-t before:border-pink-300/70"><Plug className="h-4 w-4"/></span><span className="h-px w-8 bg-pink-300/50"/><span className="text-[11px] font-bold uppercase tracking-[.24em]">Partner ecosystem</span></div><h1 className="mt-6 text-4xl font-black leading-tight sm:text-6xl">Connect your infrastructure to Africa’s event economy.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/70">Merry Tales brings together commerce, gifting, planning, invitations, messaging and fulfilment. We are building with regulated and trusted partners—not pretending one platform should own every layer.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="mailto:partners@merrytales.co.ke?subject=Merry%20Tales%20partnership"><Button className="rounded-full px-8 py-6 font-bold">Become a partner <ArrowRight className="ml-2 h-4 w-4"/></Button></a><a href="#framework"><Button variant="outline" className="w-full rounded-full border-white/25 bg-transparent px-8 py-6 font-bold text-white hover:bg-white/10">View integration framework</Button></a></div></div><div className="grid grid-cols-2 gap-4"><div className="rounded-3xl bg-white/10 p-6"><p className="text-3xl font-black text-pink-300">Commerce</p><p className="mt-2 text-sm text-white/60">Marketplace and corporate procurement</p></div><div className="rounded-3xl bg-white/10 p-6"><p className="text-3xl font-black text-pink-300">Gifting</p><p className="mt-2 text-sm text-white/60">Registries, rewards and experiences</p></div><div className="rounded-3xl bg-white/10 p-6"><p className="text-3xl font-black text-pink-300">Reach</p><p className="mt-2 text-sm text-white/60">Guests, vendors and organizations</p></div><div className="rounded-3xl bg-white/10 p-6"><p className="text-3xl font-black text-pink-300">Trust</p><p className="mt-2 text-sm text-white/60">Verified, auditable integrations</p></div></div></div></section>
    <section className="border-b bg-[#fffdfb] px-4 py-14 sm:px-6"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Sample target ecosystem</p><h2 className="mt-2 text-2xl font-black sm:text-4xl">Brands customers already recognize.</h2></div><p className="max-w-xl text-sm leading-6 text-gray-500">Shown as potential integration targets only. This is not a claim of partnership, endorsement or live availability.</p></div><div className="mt-8 grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-6">
      <a href="https://giftpesa.com/" target="_blank" rel="noreferrer" className="group grid min-h-28 place-items-center rounded-2xl border bg-white p-4 text-center shadow-sm"><span className="text-2xl font-black tracking-tight text-[#0c8040]">Gift<span className="text-[#f5a800]">Pesa</span></span><small className="mt-2 block text-[10px] font-bold uppercase tracking-wider text-gray-400">Voucher target</small></a>
      <a href="https://www.ezawadi.co.ke/" target="_blank" rel="noreferrer" className="grid min-h-28 place-items-center rounded-2xl border bg-white p-4 text-center shadow-sm"><span className="text-2xl font-black italic tracking-tight text-[#5c2d91]">e<span className="text-[#ee2b7b]">Zawadi</span></span><small className="mt-2 block text-[10px] font-bold uppercase tracking-wider text-gray-400">Rewards target</small></a>
      <div className="grid min-h-28 place-items-center rounded-2xl border bg-white p-4 text-center shadow-sm"><img src="/partners/kenya-airways.svg" alt="Kenya Airways" className="h-10 max-w-full object-contain"/><small className="mt-2 block text-[10px] font-bold uppercase tracking-wider text-gray-400">Travel gift target</small></div>
      <a href="https://www.jambojet.com/" target="_blank" rel="noreferrer" className="grid min-h-28 place-items-center rounded-2xl border bg-white p-4 text-center shadow-sm"><span className="text-2xl font-black lowercase tracking-tight text-[#e40474]">jambojet</span><small className="mt-2 block text-[10px] font-bold uppercase tracking-wider text-gray-400">Experience target</small></a>
      <div className="grid min-h-28 place-items-center rounded-2xl border bg-white p-4 text-center shadow-sm"><span className="text-2xl font-black tracking-tight text-[#39a935]">M‑PESA</span><small className="mt-2 block text-[10px] font-bold uppercase tracking-wider text-gray-400">Payment rail target</small></div>
      <a href="https://mobilesasa.com/" target="_blank" rel="noreferrer" className="grid min-h-28 place-items-center rounded-2xl border bg-white p-4 text-center shadow-sm"><span className="text-xl font-black tracking-tight text-[#171735]">Mobile<span className="text-primary">Sasa</span></span><small className="mt-2 block text-[10px] font-bold uppercase tracking-wider text-gray-400">Messaging target</small></a>
    </div><p className="mt-5 text-xs leading-5 text-gray-400">Company names and trademarks belong to their respective owners. Brand assets require permission and validation before a commercial launch.</p></div></section>
    <section className="px-4 py-20 sm:px-6"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Where partners fit</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">One ecosystem. Clear responsibilities.</h2><p className="mt-4 text-lg leading-8 text-gray-600">Named organizations are potential ecosystem fits, not claims of an existing integration. Every relationship moves through due diligence, contracting, sandbox testing and launch approval.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{partnerTypes.map(({icon:Icon,title,names,copy})=><article key={title} className="rounded-3xl border bg-[#fffdfb] p-6"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-primary/10 text-primary"><Icon/></div><h3 className="mt-5 text-xl font-extrabold">{title}</h3><p className="mt-1 text-xs font-bold uppercase tracking-wider text-primary">{names}</p><p className="mt-3 leading-7 text-gray-600">{copy}</p></article>)}</div></div></section>
    <section id="framework" className="border-y bg-gray-50 px-4 py-20 sm:px-6"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><div><div className="grid h-14 w-14 place-items-center rounded-2xl bg-green-100 text-green-700"><ShieldCheck/></div><h2 className="mt-5 text-3xl font-black">Trust before launch.</h2><p className="mt-4 text-lg leading-8 text-gray-600">A logo wall is not an integration strategy. Partners receive the minimum data needed, users know who provides each regulated service, and every transaction can be reconciled.</p></div><div className="grid gap-3">{integrationRules.map(rule=><div key={rule} className="flex items-start gap-3 rounded-2xl border bg-white p-4 font-semibold"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-green-600"/>{rule}</div>)}</div></div></section>
    <section className="px-4 py-20 text-center sm:px-6"><div className="mx-auto max-w-3xl"><h2 className="text-3xl font-black sm:text-5xl">Build the next event-economy integration with us.</h2><p className="mt-4 text-lg text-gray-600">Tell us what you provide, the markets you cover, your regulatory status and the customer journey you want to improve.</p><a href="mailto:partners@merrytales.co.ke?subject=Merry%20Tales%20integration"><Button className="mt-8 rounded-full px-9 py-6 font-bold">Start a partnership conversation <ArrowRight className="ml-2 h-4 w-4"/></Button></a></div></section>
  </div>;
}
